### ISSUE TITLE
Option to output to GIF/MP4?

### ISSUE THREAD

**Issue by dannguyen** [google/gif-for-cli#1]
I realize this feature would be the absolute height of software-generated waste but would be helpful for sharing the results online and on social media :)

**Comment by Androbin** [comment]
That can be done with the tools `ttyrec`, `tty2gif` and `imagemagick`.
Here's a guide on how to use it (See section "Converting into a .gif"):
https://www.howtoforge.com/tutorial/how-to-record-your-terminal-session-on-linux/

**Comment by teaearlgraycold** [comment]
You could share the output losslessly if you use [asciinema](https://asciinema.org/)

**Comment by Androbin** [comment]
@teaearlgraycold `asciinema` can't and never will be able to produce video (or gif) output:
https://github.com/asciinema/asciinema-server/issues/189

**Comment by dannguyen** [comment]
Thanks @Androbin, didn't know about those utilities!

**Comment by teaearlgraycold** [comment]
@Androbin I'm aware. But the recordings can be shared.

**Comment by SeanHayes** [comment]
This feature will be shipping shortly (today).

**Comment by SeanHayes** [comment]
Released, you can now do `--export=foo.gif` or `--export=foo.mp4` (or probably any format ffmpeg supports).
