### ISSUE TITLE
Python3 devel requirement

### ISSUE THREAD

**Issue by jcubic** [google/gif-for-cli#3]
The readme needs updating with this requirement if you don't install python devel it will fail to compile because of missing Python.h file.

**Comment by jcubic** [comment]
I've lost my console output, because I've run the app in the same terminal. I'm on Fedora. invoking `sudo dnf isntall python3-devel` solve the problem.

**Comment by jcubic** [comment]
I can remove the package and see what's failing if you want.

**Comment by SeanHayes** [comment]
Does your Python env have wheel support? If so I think pip should install a precompiled version of Pillow, if not, then it'll try to compile from source.

**Comment by jcubic** [comment]
How can I test this? I've called `pip3 install --user wheel` and it was installed.

**Comment by SeanHayes** [comment]
It'll be hard to untangle the cause now that everything is installed. I'll add a note to the README that python-dev/python-devel may be required.
