### ISSUE TITLE
Process and play in separate calls

### ISSUE THREAD

**Issue by marek-saji** [google/gif-for-cli#6]
Would be nice to be able to process the image and play it in separate steps.

Use case: Play a gif after an operation. Pasing can be done earlier so that user does not have to wait for celebratory animation.

```sh
gif-for-cli --output=yay.cligif "yay" & # probably something like --quiet would be a good idea
PROC_PID=$!

# … do something

# celebrate
wait $PROC_PID
if [ -r yay.cligif ]
then
  gif-for-cli yay.cligif
  rm yay.cligif
fi
```

Most (all?) of the options would be valid with `--output`, but not when playing processed gif.

**Comment by SeanHayes** [comment]
Thanks for the idea, I added a `--no-display` option.
