### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by quinton-ashley** [google/gif-for-cli#8]

**Comment by SeanHayes** [comment]
Could you elaborate?

**Comment by quinton-ashley** [comment]
Why waste your time on such a stupid and pointless idea?  Even after all that work the end result looks like garbage.  Not enough to do at google?  How's the self-driving car team doing?  Could they not use some help?  People are literally dying in preventable car crashes everyday while you guys waste time on this trash.

**Comment by OvermindDL1** [comment]
@quinton-ashley For note, even if these were the people that worked on the cars (which I doubt), most programmers tend to need 'fun' projects like this on occasion to help clean and reset the brain.  Things like this can substantially improve productivity when working on the more heavy/difficult problems.

**Comment by quinton-ashley** [comment]
Yeah at first I thought these kind of pointless joke repos were funny, like the equivalent of youtube poops of the open source programming world.  But then I started thinking that programmers have more social responsibility than some random dude with MSPaint and the trial version of Resolve.  I looked back in there commit history and there's been active work on it since April 19th.  I understand the need for 'fun' projects on occasion but I feel like this crosses the line ya know?  I'm not against joke repos in general, I made one called [hendriks](https://github.com/quinton-ashley/hendriks), but I think good joke repos are simple ideas that can be done in a few hours, not multi-month projects.

**Comment by SeanHayes** [comment]
@quinton-ashley I initially assumed you must be some random person who joined GitHub just to complain, but when I looked at your profile I saw you're a pretty prolific coder, whose profile is filled with video game re-skins and other projects that are less than strictly necessary to the future of humanity.

**Comment by quinton-ashley** [comment]
While not strictly necessary to the future of humanity the important distinction is those projects aren't joke repos and they're not pointless.

**Comment by quinton-ashley** [comment]
At best a joke repo can inspire young people to take an interest in computer science.  At worst they are pointless, multi-month long, masturbatory displays of wasted productivity that somehow manage to get over 1,000 stars on github.

**Comment by SeanHayes** [comment]
I don't know what you mean by a "joke repo", this is an actual program that can be installed and run. As for pointless, that's a matter of opinion; replacing textures in video games or creating a repo for changing whitespace could easily be labelled pointless.

I'm not sure how you found this project, but perhaps this will shed some light:
https://opensource.googleblog.com/2018/06/tenor-gif-for-cli.html

You wanted higher res textures in your games, I wanted an animated GIF to show up when I SSH into my workstation (and I wanted to share the code I used to do that), big diff.

**Comment by quinton-ashley** [comment]
These are all fun projects but I think if you asked the Dolphin developers and texture packing community if what they were doing could be as easily labelled a joke or pointless I think they would strongly disagree.  I think Dolphin and texture packs do have some real value to humanity in terms of both cultural preservation and enhancement of older video game software for future generations.  `hendriks` can actually be installed and run too but I would label it a joke repository because I made it so that people who've watched Silicon Valley could read the readme and at most, test it out and have a quick laugh.

I will admit I was wrong though, this isn't a joke repository or pointless to you if you're actually going to use it day to day.  I like ASCII art and moving ASCII art is cool too but I was certain this repo was a joke because watching such a poor quality degradation of a gif in a terminal window is kind of ridiculous when you could just watch it in the browser in "full" quality.  ("full" in quotes for the Deadpool 2 gif because the film was shot in 3.4k so the gif is also degradation, as many gifs are.  I probably would've had trouble recognizing it without seeing the original gif.)

After reading your blog post and your last sentence in the comment above I can tell that you would label this repo an art project and not a joke so I apologize for my interpreting it as such.  Sorry for attacking you without all the information, I wouldn't have if I had read the blog post first.  I found this repo from the github trending page and read through the readme.

**Comment by quinton-ashley** [comment]
I'm sorry for being an idiot years ago when I complained about this project apparently being "a waste of your time" idk what the hell I was thinking, I wasn't. It's actually pretty cool and I can appreciate it now that I have a better understanding of programming, politics, and the world in general. I used be pretty libertarian and read Wired magazine like the bible and thought programmers at Google were like gods that could do anything, solve world hunger and shit lol.

So again I'm sorry and you were right. Could you delete this issue please?
https://docs.github.com/en/enterprise-server@2.21/github/managing-your-work-on-github/deleting-an-issue
