### ISSUE TITLE
Subgif feature

### ISSUE THREAD

**Issue by taylorKonigsmark** [google/gif-for-cli#9]
Could we get a feature to make a sub gif out of a main one?

Something like:
`gif-for-cli --start-time 3s --end-time 5s`

The above command would make a 2 second gif out of the original

**Comment by alashow** [comment]
Isn't this out of scope of this project?
I think it's only a "gif to animated ASCII art converter" and not some gif manipulation tool.

But [ffmpeg](https://ffmpeg.org) can do what you want:
```
ffmpeg -i input.gif -ss 00:00:03 -t 00:00:05 -async 1 output.gif
```
(`-ss` is for the start time, `-t` is for the duration after `-ss`)

**Comment by SeanHayes** [comment]
Thanks for the suggestion, but I think this would be out of scope.
